#!/bin/bash
echo "Starting SF Weekend Planner Expert System..."
echo "=========================================="
echo ""
echo "To run the expert system:"
echo "1. Activate the virtual environment: source venv/bin/activate"
echo "2. Run the expert system: python expert_system.py"
echo ""
echo "The system will ask you questions about your preferences and recommend"
echo "places to visit in San Francisco for the weekend!"
echo ""
echo "Example questions you'll be asked:"
echo "- Do you prefer indoor or outdoor locations?"
echo "- What's your budget per person?"
echo "- What kind of vibe are you looking for?"
echo "- How far are you willing to travel?"
echo "- Do you need WiFi, plugs, food availability?"
echo "- Do you prefer quiet or crowded places?"
echo "- Do you need wheelchair accessibility?"
echo ""
echo "Ready to start? Run: source venv/bin/activate && python expert_system.py"
